### ISSUE TITLE
Vue app called to many times on multiple page load

### ISSUE THREAD

**Issue by ArnoHolo** [jeffreyguenther/vue-turbolinks#11]
Hi there,

I've followed the Readme tutorial but it seems I can't make this package work right.

I want my Vue app (in a specific JS file) to work on a specific page. I call the JS file from the bottom of the haml view file with javascript_pack_tag helper.

There are several situations:

1. I load my new.html.haml page : my Vue app is called. ✅ 

2. I load another page (such as index.html.haml), then I click on a link going to new.html.haml page : my Vue app is not called. 🚫 From what I read here https://github.com/rails/webpacker/issues/354 it seems that turbolinks:load is called before the JS file is processed. 

3. I load my new.html.haml page : my Vue app is called. I click on a link going to new.html.haml page : my Vue app is called again. I click once again on this link, and the Vue message is displayed two times in console instead of one 🚫 (the number goes from 2 to 4):

<img width="500" alt="screen shot 2017-07-24 at 12 28 29" src="https://user-images.githubusercontent.com/6376958/28519399-afb98c04-706b-11e7-855d-415aa641f2cf.png">

Then I click a last time on this link, and everything goes wrong 🚫 🚫 🚫:

<img width="1325" alt="screen shot 2017-07-24 at 12 02 46" src="https://user-images.githubusercontent.com/6376958/28519245-2846a81a-706b-11e7-86c1-57a5ad3b7b60.png">

Here are my files:

my_specific_controller/new.html.haml:
```
#my-specific-div
    %template{'v-if' => 'hello'}= 'Hi there'
    %template{'v-if' => 'bye'}= 'Bye bye'

= javascript_pack_tag 'specific_controller/new'
```

javascript/packs/specific_controller/new.js:
```js
import Vue from 'vue/dist/vue.esm'
import TurbolinksAdapter from 'vue-turbolinks'

Vue.use(TurbolinksAdapter)     

document.addEventListener('turbolinks:load', () => {
    var element = document.getElementById('my-specific-div')
    if (element != null) {
        new Vue({
            el: '#my-specific-div',
            data: {
                hello: true,
                bye: false
            }
        })
    }
})
```

I suppose the `javascript_pack_tag` is called each time the page is loaded, so I should remove the event listener (`document.removeEventListener('turbolinks:load')`) before adding another one, but then my JS scripts would become a bit verbose (they already are, with `addEventListener`, `getElementById` and `if (element != null)`).

What do you think of it? 🐢

**Comment by ArnoHolo** [comment]
All right, when I precise turbolinks evaluation (`= javascript_pack_tag specific_controller/new', data: {turbolinks_eval: false}`), problem n°3 is solved, but not problem n°2.

I managed to solve both problems by moving `javascript_pack_tag` line (without `turbolinks_eval`) in my layout `<head>`, which would be verbose if I have a lot of JS files but, hey, it's working. ¯\\\_(ツ)\_/¯

**Comment by excid3** [comment]
@ArnoHolo If you're going to be including the Javascript only on certain pages, that code won't be affected by Turbolinks at all and you don't need this library. 

Turbolinks will run script tags in the body on each page request so if you plan to keep including the javascript_pack_tag in the body, then you can get rid of vue-turbolinks and you should be all good.

This library is for Javascript that's included on every page. Turbolinks events are the way to trigger that code to be run on each page view when your JS is included in the head and on every page.

**Comment by tsmith-dev** [comment]
@excid3 Would you need this library if you're using something like...

// in the view
```
<% content_for :head %>
  <%= javascript_pack_tag 'my_vue_app', 'data-turbolinks-track': 'reload' %>
<% end %>
```

// in the layout
```
<head>
  <% if content_for :head %>
    <%= yield :head %>
  <% end %>
</head>
```

**Comment by excid3** [comment]
I don't know, but you can try it without and see.
