### ISSUE TITLE
Purpose of vue-turbolinks

### ISSUE THREAD

**Issue by ytbryan** [jeffreyguenther/vue-turbolinks#2]
Thanks for this plugin. 

I'm trying to understand the purpose of `vue-turbolinks`. I found this plugin through the issue on vue repo.

Is the purpose of vue-turbolinks to fix the memory issues of un-mounting Vue components when turbolinks is switched on? If not, can you please explain :)

**Comment by jeffreyguenther** [comment]
The purpose of this mixin is to allow Vue to play nicely with Turbolinks' caching mechanism. When Vue setups a component it changes the HTML of the element it mounts onto, which is expected. This is how we get the features of Vue. However, when a component is destroyed it doesn't return the DOM to the pre-mount state. This mixin does that by defining lifecycle methods that clean up the DOM so it can be cached by Turbolinks.

There might be memory issues lurking beneath the surface, but that wasn't our goal when we wrote it. We wanted to use Vue alongside Turbolinks.
