### ISSUE TITLE
Navigation with browser back/forward buttons no longer works in 2.0.2

### ISSUE THREAD

**Issue by danieldiekmeier** [jeffreyguenther/vue-turbolinks#22]
Hey there, first of: Thank you for this package, it really helps.

After upgrading from 2.0.1 to 2.0.2, I noticed a regression: When navigating with the browsers back/forward buttons, my Vue instances are not recreated. The DOM is still correct, but event handlers are not attached anymore.

I think it has to to with this commit: (mainly because there weren't any others)
https://github.com/jeffreyguenther/vue-turbolinks/commit/14351a99b46e96739bc984c303a86241198c2ef5

The Event changed from `turbolinks:visit` to `turbolinks:before-render`, that's probably the problem? I'm not sure.

I'm back on 2.0.1 for the time being, which still works great!

I hope this is clear and useful. If the problem is not obvious, I can also try to add a reproduction.

**Comment by excid3** [comment]
Ah shoot, you're right. I had thought there was something wrong with that and forgot to test that piece. 

I just published 2.0.3 which fixes the regression. It also keeps the override so you can override the turbolinks event still.

**Comment by danieldiekmeier** [comment]
Wow, thanks for handling this so fast!
