### ISSUE TITLE
Issue with Vue Turbolinks and Laravel Spark Install

### ISSUE THREAD

**Issue by jhull** [jeffreyguenther/vue-turbolinks#23]
Sry if this isn't the place to post this, but I can't find anyone with same problem.

Fresh install of latest Laravel w/ Spark. Everything works great if `app.js` is in `<body>`, but the moment I move to suggested '<head>` everything stops working.

If I put it before Spark scripts in head, I get `Spark not defined` error. If I put at the end of `<head>` I get `Vue not defined`.

Would love to get all of these playing nice together.

**Comment by tallredmanxyz** [comment]
I'm also having this issue and currently investigating. Did you find any workarounds?

**Comment by hassanazimi** [comment]
So I guess what happens is app trying to pass data to `window.Spark` object on the `<head>` but for some reason the data don;t go through.

**Comment by azimidev** [comment]
Found it:

In your `spark-bootstrap` file, you have this condition:

```
if ($('#spark-app').length > 0) {
    require('vue-bootstrap');
}
```

just remove the if condition because it checks in the dom with jQuery to see if we have element with ID of `spark-app`.
