### ISSUE TITLE
Issue with components that need to access $el.parentNode after component destruction

### ISSUE THREAD

**Issue by alexisagos** [jeffreyguenther/vue-turbolinks#28]
Hi,

First of all, thanks for the great mixin !

I have come across an error caused by the adapter when using a vue component library ([Element UI](http://element.eleme.io/)). [The Message component](http://element.eleme.io/?ref=madewithvuejs.com#/en-US/component/message) that displays a message at the top of the page that then disappears is causing a bug because at one point it needs to access the component's $el.parentNode after having destroyed it but because of the vue-turbolinks adapter, the element's outerHTML has been modified and parentNode is null.

> Cannot read property 'removeChild' of null

I have reproduced this issue here:
[https://codesandbox.io/s/j4k708vzy5](https://codesandbox.io/s/j4k708vzy5)

Is there a way to prevent this issue from happening at the adapter level ?

**Comment by excid3** [comment]
Hmm, probably. I'm not sure how Element inserts the item onto the page. May have to dig into Element's Message component and see how it handles things.
