### ISSUE TITLE
A note for people experiencing NoModificationAllowedError: Failed to set the 'outerHTML' property on 'Element'

### ISSUE THREAD

**Issue by mattlima** [jeffreyguenther/vue-turbolinks#33]
Hey there, and thanks for the great software! I wanted to contribute a note that might save some other users some time but I'm not sure how to do so. We have a Rails app with vue-turbolinks on the front end, and we were experiencing intermittent `DOMException: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.` errors. The problem turned out to be using a component where the root was wrapped in a transition. 

Render call: 
```
    new Vue({
      el: $our_root_element,
      components: { AjaxModal },
      data() {
        return {vdata: base_data};
      },
      template: '<AjaxModal v-bind:vdata="vdata"/>'
    });
```

And the AjaxModal component starts like:
```
<template>
    <transition name="modal">
      <div v-if="vdata.ui_state.show" class="modal">
...
```

If the ajax modal was mounted on a page and then dismissed, we would get the DOM exception on the next turbolinks visit. The solution was to ensure the root component did not start with a `<transition>`: 

```
<template>
  <div>
    <transition name="modal">
      <div v-if="vdata.ui_state.show" class="modal">
...
```

Hope this helps someone else - might be worth a note in the README?

**Comment by excid3** [comment]
Good catch @mattlima! Do you want to make a PR for adding that to the readme? 👍
