### ISSUE TITLE
Buefy Snackbar and Toast shown only first time

### ISSUE THREAD

**Issue by mrdahbi** [jeffreyguenther/vue-turbolinks#35]
Hi,

I'm using vue-turbolinks ([globally](https://github.com/jeffreyguenther/vue-turbolinks#mixin-option-1-global)) alongside Buefy components and it's been working great.

I'm now facing an issue where [Snackbars](https://buefy.org/documentation/snackbar) and [Toasts](https://buefy.org/documentation/toast) aren't shown the second and subsequent times they are triggered and there are no console errors.
Disabling `vue-turbolinks` restores the expected behavior of the snackbar, so the issue is most certainly in how turbolinks loads these components.

Many thanks.

`vue 2.6.12`
`buefy 0.9.3`
`vue-turbolinks 2.1.0`

**Comment by excid3** [comment]
Since I don't use Buefy, you'll have to submit an example app that replicates the problem. 

You might need to build a custom integration for those depending on how Buefy implements them. vue-turbolinks is only saving the original HTML and restoring it before turbolinks navigates to a new page, nothing fancy. If Buefy is doing things outside of that scope, then vue-turbolinks won't handle it and you will need to build a workaround.

**Comment by mrdahbi** [comment]
The issue as I understand it comes from Buefy attaching snackbars and toasts to the body element and this is outside the element where Vue was mounted.

Buefy does have an option to set the container element but couldn't get it to work.
I'm wondering if anyone has had the same issue.

[edit] I just noticed that Snackbar has transition as root element of the component ([src](https://github.com/buefy/buefy/blob/master/src/components/snackbar/Snackbar.vue)). It may be the issue as described in the vue-turbolinks readme.

Thanks again !

**Comment by excid3** [comment]
Ah yep, if it's doing things outside of where Vue is mounted then it isn't going to be handled by vue-turbolinks because we won't know about the change.

**Comment by mrdahbi** [comment]
After many trials and errors, I found a workaround by using `vue-turbolinks` as a mixin and not as a global plugin.
I have posted an issue on Buefy's repo: https://github.com/buefy/buefy/issues/2969

**Comment by excid3** [comment]
Great! Thanks for sharing your solution.

**Comment by mrdahbi** [comment]
> Great! Thanks for sharing your solution.

Thank you for your awesome tutorials !
