### ISSUE TITLE
[Vue warn]: Cannot find element: #video_list

### ISSUE THREAD

**Issue by Davidzhu001** [jeffreyguenther/vue-turbolinks#4]
something need to click twice for the rails link in order to show content

```
import Vue from 'vue/dist/vue.esm'
import Videos from './videos/videos.vue'
import TurbolinksAdapter from 'vue-turbolinks';
document.addEventListener('turbolinks:load', () => {
  var vueapp = new Vue({
    el: "#video_list",
    template: '<Videos/>',
    mixins: [TurbolinksAdapter],
    components: { Videos }
  });

});


```

**Comment by excid3** [comment]
@Davidzhu001 Check out this in the Readme: https://github.com/jeffreyguenther/vue-turbolinks#running-vue-only-on-specific-pages

If you have a page that doesn't include the element, you don't want to initialize the Vue app on that page.

**Comment by Davidzhu001** [comment]
@excid3 thanks for your reply.

I found a problem of using this gem.


```
import Vue from 'vue/dist/vue.esm'
import Downloads from './components/downloads.vue'
import TurbolinksAdapter from 'vue-turbolinks';


document.addEventListener('turbolinks:load', () => {
  var element = document.getElementById("downloads")
  if (element != null) {
  var downloads_vue = new Vue({
    el: element,
    template: '<Downloads/>',
    mixins: [TurbolinksAdapter],
    components: { Downloads }
  });
  } 
  else {
    console.log('not found element')
  }
      console.log('event touched')

});
---
<div id="downloads">
   
</div>
<%= javascript_pack_tag 'downloads' %>

```


![image](https://cloud.githubusercontent.com/assets/9436230/25872414/37c87d08-34d0-11e7-991f-285ed5d1f7de.png)

**Comment by Davidzhu001** [comment]
the code <%= javascript_pack_tag 'downloads' %>
 will called after turbolinks:loaded.

**Comment by excid3** [comment]
@Davidzhu001 I don't quite understand what your issue is. Can you explain it some more?

**Comment by jeffreyguenther** [comment]
@Davidzhu001 are you still looking for assistance or can this issue be closed?

**Comment by jeffreyguenther** [comment]
Closing b/c issue is stale.
