### ISSUE TITLE
Doesn't work with the new version of hello_vue.js

### ISSUE THREAD

**Issue by shcyiza** [jeffreyguenther/vue-turbolinks#5]
This is the new version of vue.js that comes with the updated webpacker...
Notice how the vue app is call in the html by a stylesheet_pack_tag method.
Is there anyway to make that work?
```
/* eslint no-console: 0 */
// Run this example by adding <%= javascript_pack_tag 'hello_vue' %> and
// <%= stylesheet_pack_tag 'hello_vue' %> to the head of your layout file,
// like app/views/layouts/application.html.erb.
// All it does is render <div>Hello Vue</div> at the bottom of the page.

import Vue from 'vue'
import App from './app.vue'

document.addEventListener('turbolinks:load', () => {
  document.body.appendChild(document.createElement('hello'))
  const app = new Vue(App).$mount('hello')

  console.log(app)
})
```

**Comment by excid3** [comment]
You'll need to add it as a mixin inside the app.vue file now. You can do the same import and mixins inside that file.

**Comment by shcyiza** [comment]
OMG u quick! lol.
Follow your instructions. It worked!
Here is an exemple of what u need to add in app.vue:
```
<script>
import TurbolinksAdapter from 'vue-turbolinks'

export default {
  data: function () {
    return {
      message: new Date
    }
  },
  mixins: [TurbolinksAdapter]
}
</script>
```
Thanks for the quickest and most efficient support ever :p

**Comment by excid3** [comment]
I do my best to be quick. :D Glad that worked!

I'll be updating the example in the readme as well so you can reference that easily in the future. 👍
